### ISSUE TITLE
Modrinth and CurseForge Links

### ISSUE THREAD

**Issue by SkyKingPX** [NewAmazingPVP/AutoUpdatePlugins#10]
Hello,
I wanted to ask if Modrinth and CurseForge links are working in the list.yml.

if not, it would be nice to see it in the next update 😉

**Comment by NewAmazingPVP** [comment]
Hey there, @SkyKingPX, I am so sorry for being so late; I almost forgot about this. I have added beta Modrinth support and am working on CurseForge. Here is the build: https://cdn.discordapp.com/attachments/1103725182314614834/1249489425402953789/autoupdateplugins-modrinthSupport.jar?ex=66677d35&is=66662bb5&hm=a70fdb2c3ebfe1d09e696843d2fdbeff88b5d5ca7c11110168799b4dbaa2ea46&). Because of how modrinth links are currently, you want to put it this way: [modrinth like] [project ID] like https://modrinth.com/plugin/simple-voice-chat/9eGKb6K1. You can get the project ID at the at the bottom left of the page. ![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/87737759/317c72d7-f63f-42a8-899f-62cd8f2ecda3)

**Comment by NewAmazingPVP** [comment]
Please test it out and let me know if it works as intended.

**Comment by SkyKingPX** [comment]
Thank you, I will

**Comment by NewAmazingPVP** [comment]
Hey @SkyKingPX, you can also try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1249752472587731004/autoupdateplugins-1.0.jar?ex=66687230&is=666720b0&hm=aaa3ad0d068639ec2d84a1d0bce0097545a1c22e7dab19a0e748296f55f8aec5&), it should make it so you can directly put the link in without projectID and should work. The only downside right now is that it only supports spigot jars, but I am working on adding others.

**Comment by SkyKingPX** [comment]
So try both?

**Comment by NewAmazingPVP** [comment]
Actually, I am sorry for all the confusion, just try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1249753786268909660/autoupdateplugins-1.0.jar?ex=66687369&is=666721e9&hm=48f1971a452ad5f00a3b6886ff4af57d46573599c1acafa92467d15d6a0115a8&). It has support for all platforms

**Comment by NewAmazingPVP** [comment]
Just try that one only, thanks!

**Comment by SkyKingPX** [comment]
@NewAmazingPVP But it is a plugin. Or is it a mod? The question is if I can download Mods on Forge/Fabric and Plugins from CurseForge and Modrinth. The picture that you posted confuses me...

**Comment by NewAmazingPVP** [comment]
Hey, this is a plugin, don't worry too much about the picture, as it might confuse you more. Basically, for example, voicemod is a bukkit plugin, and if you put this link in https://modrinth.com/plugin/simple-voice-chat, it should automatically update to its latest version.

**Comment by SkyKingPX** [comment]
Oh wow I didn't know that it is also a plugin

**Comment by NewAmazingPVP** [comment]
@SkyKingPX It will automatically detect if it is a mod or plugin, and it will only download plugins.

**Comment by NewAmazingPVP** [comment]
> Oh wow I didn't know that it is also a plugin

Yeah, it's both a mod and a plugin, it will only download its plugin jar though based on what platform.

**Comment by SkyKingPX** [comment]
@NewAmazingPVP I can't download the file. The speed is way to slow. I can download other files but not that one

**Comment by SkyKingPX** [comment]
![grafik](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/95442431/25de0d0f-4d67-46c4-9367-0dceeb5d3385)

**Comment by NewAmazingPVP** [comment]
Ok, no pressure whenever it works. Also, you can choose your own modrinth plugin to test it out and don't have to use voicemod. I just showed that as an example.

**Comment by NewAmazingPVP** [comment]
But thanks for your help!

**Comment by SkyKingPX** [comment]
I used "SimpleVoiceChat: https://modrinth.com/plugin/simple-voice-chat" but it didn't save the file - it isn't in the plugins folder

**Comment by NewAmazingPVP** [comment]
Alright, looking into it!

**Comment by SkyKingPX** [comment]
In this time I'll try changing the link

**Comment by SkyKingPX** [comment]
"SimpleVoiceChat: https://modrinth.com/plugin/simple-voice-chat**/**" didn't work either

**Comment by SkyKingPX** [comment]
It is also stuck, so it doesn't download the plugins after this entry in the list.yml

**Comment by NewAmazingPVP** [comment]
@SkyKingPX I fixed it, it was a simple issue that it didn't retrieve the project id. Here's the [build](https://cdn.discordapp.com/attachments/1103725182314614834/1249760491316707420/autoupdateplugins-1.0.jar?ex=666879a8&is=66672828&hm=36db61d535979687ba757ebcfb4ace3f4b800e9999853ee0042f0c38d8474d6a&)

**Comment by SkyKingPX** [comment]
@NewAmazingPVP Yes Modrinth works now.
Now I'll try CF

**Comment by SkyKingPX** [comment]
@NewAmazingPVP 
```
[18:28:48 INFO]: [AutoUpdatePlugins] [STDOUT] Failed to download plugin: Server returned HTTP response code: 403 for URL: https://www.curseforge.com/minecraft/bukkit-plugins/worldedit/
[18:28:48 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.curseforge.com/minecraft/bukkit-plugins/worldedit/
[18:28:48 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2011)
[18:28:48 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602)
[18:28:48 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[18:28:48 WARN]: 	at autoupdateplugins-1.0.jar//common.UpdatePlugins.updatePlugin(UpdatePlugins.java:55)
[18:28:48 WARN]: 	at autoupdateplugins-1.0.jar//common.UpdatePlugins.lambda$readList$0(UpdatePlugins.java:183)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[18:28:48 WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by NewAmazingPVP** [comment]
Hey, @SkyKingPX, so I looked in CF, but I have to sadly mention that I cannot add that because of the terms in their API. 
Here's the reason: https://github.com/CubeCoders/AMP/issues/686  (Tldr: It can cost money for calls.)
Plus, authors of plugins on CurseForge have the option to disallow users from downloading their mods. So therefore, with the reasons in that thread and such, I would like to stay away from CF. That being said, I have added support for dev.bukkit.org and other platforms that have all the plugins that CF has. Unless I am mistaken, are there any plugins exclusive to CF?

**Comment by NewAmazingPVP** [comment]
@SkyKingPX Try this link, https://dev.bukkit.org/projects/worldedit That should work!

**Comment by NewAmazingPVP** [comment]
Almost all curseforge plugins have alternative on bukkit.org, which already has a support.

**Comment by SkyKingPX** [comment]
> Unless I am mistaken, are there any plugins exclusive to CF?
I don't know.


> @SkyKingPX Try this link, https://dev.bukkit.org/projects/worldedit That should work!
I used this one before

**Comment by SkyKingPX** [comment]
But still thanks for at least Modrinth :)

**Comment by NewAmazingPVP** [comment]
But thank you for your help testing this out. And anytime, I am glad to implement any ideas you have!

**Comment by SkyKingPX** [comment]
> @SkyKingPX I am confused, does this link not work? https://dev.bukkit.org/projects/worldedit If so I have to fix that.

It does

**Comment by SkyKingPX** [comment]
No error and the timestamp is also correct
![grafik](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/95442431/01ff7406-cd00-45a4-a838-dadb4985db70)
![grafik](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/95442431/88ad4bf4-fda1-454f-b48e-530adb4a91b7)

**Comment by NewAmazingPVP** [comment]
Perfect, great!
